const SIGN_UP = 'SIGN_UP';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

const SIGN_IN = 'SIGN_IN';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

const ADD_RECIPE = 'ADD_RECIPE';
const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR';

const FETCH_ALL_RECIPES = 'FETCH_ALL_RECIPES';
const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS';
const FETCH_ALL_RECIPES_ERROR = 'FETCH_ALL_RECIPES_ERROR';

const FETCH_RECIPE = 'FETCH_RECIPE';
const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
const FETCH_RECIPE_ERROR = 'FETCH_RECIPE_ERROR';

const FETCH_MOST_FAVOURITED_RECIPE = 'FETCH_MOST_FAVOURITED_RECIPE';
const FETCH_MOST_FAVOURITED_RECIPE_SUCCESS = 'FETCH_MOST_FAVOURITED_RECIPE_SUCCESS';
const FETCH_MOST_FAVOURITED_RECIPE_ERROR = 'FETCH_MOST_FAVOURITED_RECIPE_ERROR';

const DELETE_RECIPE = 'DELETE_RECIPE';
const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR';

const EDIT_PROFILE = 'EDIT_PROFILE';
const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';

const EDIT_RECIPE = 'EDIT_RECIPE';
const EDIT_RECIPE_SUCCESS = 'EDIT_RECIPE_SUCCESS';
const EDIT_RECIPE_ERROR = 'EDIT_RECIPE_ERROR';

const FETCH_USER_FAVOURITE_RECIPES = 'FETCH_USER_FAVOURITE_RECIPES';
const FETCH_USER_FAVOURITE_RECIPES_SUCCESS = 'FETCH_USER_FAVOURITE_RECIPES_SUCCESS';
const FETCH_USER_FAVOURITE_RECIPES_ERROR = 'FETCH_USER_FAVOURITE_RECIPES_ERROR';

const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';
const REMOVE_FROM_FAVOURITE_SUCCESS = 'REMOVE_FROM_FAVOURITE_SUCCESS';
const REMOVE_FROM_FAVOURITE_ERROR = 'REMOVE_FROM_FAVOURITE_ERROR';

const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
const ADD_TO_FAVOURITE_SUCCESS = 'ADD_TO_FAVOURITE_SUCCESS';
const ADD_TO_FAVOURITE_ERROR = 'ADD_TO_FAVOURITE_ERROR';

const FETCH_USER_RECIPES = 'FETCH_USER_RECIPES';
const FETCH_USER_RECIPES_SUCCESS = 'FETCH_USER_RECIPES_SUCCESS';
const FETCH_USER_RECIPES_ERROR = 'FETCH_USER_RECIPES_ERROR';

const FETCH_USER = 'FETCH_USER';
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

const FETCH_MOST_UPVOTED_RECIPES = 'FETCH_MOST_UPVOTED_RECIPES';
const FETCH_MOST_UPVOTED_RECIPES_SUCCESS = 'FETCH_MOST_UPVOTED_RECIPES_SUCCESS';
const FETCH_MOST_UPVOTED_RECIPES_ERROR = 'FETCH_MOST_UPVOTED_RECIPES_ERROR';

const UP_VOTE_RECIPE = 'UP_VOTE_RECIPE';
const UP_VOTE_RECIPE_SUCCESS = 'UP_VOTE_RECIPE_SUCCESS';
const UP_VOTE_RECIPE_ERROR = 'UP_VOTE_RECIPE_ERROR';

const DOWN_VOTE_RECIPE = 'DOWN_VOTE_RECIPE';
const DOWN_VOTE_RECIPE_SUCCESS = 'DOWN_VOTE_RECIPE_SUCCESS';
const DOWN_VOTE_RECIPE_ERROR = 'DOWN_VOTE_RECIPE_ERROR';

const POST_COMMENT = 'POST_COMMENT';
const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';

const FETCH_COMMENTS = 'FETCH_COMMENTS';
const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

const DELETE_COMMENT = 'DELETE_COMMENT';
const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

const ADD_OR_REMOVE_FAVOURITE = 'ADD_OR_REMOVE_FAVOURITE';
const ADD_OR_REMOVE_FAVOURITE_SUCCESS = 'ADD_OR_REMOVE_FAVOURITE_SUCCESS';
const ADD_OR_REMOVE_FAVOURITE_ERROR = 'ADD_OR_REMOVE_FAVOURITE_ERROR';

const SEARCH_RECIPE = 'SEARCH_RECIPE';
const SEARCH_RECIPE_SUCCESS = 'SEARCH_RECIPE_SUCCESS';
const SEARCH_RECIPE_ERROR = 'SEARCH_RECIPE_ERROR';

const FETCH_USER_FAVOURITE_RECIPE_Ids = 'FETCH_USER_FAVOURITE_RECIPE_Ids';
const FETCH_USER_FAVOURITE_RECIPE_Ids_SUCCESS = 'FETCH_USER_FAVOURITE_RECIPE_Ids_SUCCESS';
const FETCH_USER_FAVOURITE_RECIPE_Ids_ERROR = 'FETCH_USER_FAVOURITE_RECIPE_Ids_ERROR';

const LOGOUT = 'LOGOUT';
const SET_CURRENT_USER = 'SET_CURRENT_USER';

export default {
  SIGN_UP,
  SIGN_UP_SUCCESS,
  SIGN_UP_ERROR,
  SIGN_IN,
  SIGN_IN_SUCCESS,
  SIGN_IN_ERROR,
  ADD_RECIPE,
  ADD_RECIPE_SUCCESS,
  ADD_RECIPE_ERROR,
  FETCH_ALL_RECIPES,
  FETCH_ALL_RECIPES_SUCCESS,
  FETCH_ALL_RECIPES_ERROR,
  FETCH_RECIPE,
  FETCH_RECIPE_SUCCESS,
  FETCH_RECIPE_ERROR,
  DELETE_RECIPE,
  DELETE_RECIPE_SUCCESS,
  DELETE_RECIPE_ERROR,
  FETCH_USER,
  FETCH_USER_SUCCESS,
  FETCH_USER_ERROR,
  EDIT_PROFILE,
  EDIT_PROFILE_SUCCESS,
  EDIT_PROFILE_ERROR,
  EDIT_RECIPE,
  EDIT_RECIPE_SUCCESS,
  EDIT_RECIPE_ERROR,
  FETCH_USER_FAVOURITE_RECIPES,
  FETCH_USER_FAVOURITE_RECIPES_SUCCESS,
  FETCH_USER_FAVOURITE_RECIPES_ERROR,
  ADD_TO_FAVOURITE,
  ADD_TO_FAVOURITE_SUCCESS,
  ADD_TO_FAVOURITE_ERROR,
  REMOVE_FROM_FAVOURITE,
  REMOVE_FROM_FAVOURITE_SUCCESS,
  REMOVE_FROM_FAVOURITE_ERROR,
  FETCH_USER_RECIPES,
  FETCH_USER_RECIPES_SUCCESS,
  FETCH_USER_RECIPES_ERROR,
  UP_VOTE_RECIPE,
  UP_VOTE_RECIPE_SUCCESS,
  UP_VOTE_RECIPE_ERROR,
  DOWN_VOTE_RECIPE,
  DOWN_VOTE_RECIPE_SUCCESS,
  DOWN_VOTE_RECIPE_ERROR,
  POST_COMMENT,
  POST_COMMENT_SUCCESS,
  POST_COMMENT_ERROR,
  FETCH_COMMENTS,
  FETCH_COMMENTS_SUCCESS,
  FETCH_COMMENTS_ERROR,
  DELETE_COMMENT,
  DELETE_COMMENT_SUCCESS,
  DELETE_COMMENT_ERROR,
  ADD_OR_REMOVE_FAVOURITE,
  ADD_OR_REMOVE_FAVOURITE_SUCCESS,
  ADD_OR_REMOVE_FAVOURITE_ERROR,
  SET_CURRENT_USER,
  FETCH_MOST_UPVOTED_RECIPES,
  FETCH_MOST_UPVOTED_RECIPES_SUCCESS,
  FETCH_MOST_UPVOTED_RECIPES_ERROR,
  LOGOUT,
  SEARCH_RECIPE,
  SEARCH_RECIPE_SUCCESS,
  SEARCH_RECIPE_ERROR,
  FETCH_USER_FAVOURITE_RECIPE_Ids,
  FETCH_USER_FAVOURITE_RECIPE_Ids_SUCCESS,
  FETCH_USER_FAVOURITE_RECIPE_Ids_ERROR,
  FETCH_MOST_FAVOURITED_RECIPE,
  FETCH_MOST_FAVOURITED_RECIPE_SUCCESS,
  FETCH_MOST_FAVOURITED_RECIPE_ERROR
};
