const SIGN_UP = 'SIGN_UP';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

const SIGN_IN = 'SIGN_IN';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

const ADD_RECIPE = 'ADD_RECIPE';
const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR';

const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
const GET_ALL_RECIPES_SUCCESS = 'GET_ALL_RECIPES_SUCCESS';
const GET_ALL_RECIPES_ERROR = 'GET_ALL_RECIPES_ERROR';

const GET_RECIPE = 'GET_RECIPE';
const GET_RECIPE_SUCCESS = 'GET_RECIPE_SUCCESS';
const GET_RECIPE_ERROR = 'GET_RECIPE_ERROR';

const DELETE_RECIPE = 'DELETE_RECIPE';
const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR';

const MODIFY_RECIPE = 'MODIFY_RECIPE';
const MODIFY_RECIPE_SUCCESS = 'MODIFY_RECIPE_SUCCESS';
const MODIFY_RECIPE_ERROR = 'MODIFY_RECIPE_ERROR';

const GET_USER_FAVOURITE_RECIPES = 'GET_USER_FAVOURITE_RECIPES';
const GET_USER_FAVOURITE_RECIPES_SUCCESS = 'GET_USER_FAVOURITE_RECIPES_SUCCESS';
const GET_USER_FAVOURITE_RECIPES_ERROR = 'GET_USER_FAVOURITE_RECIPES_ERROR';

const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';
const REMOVE_FROM_FAVOURITE_SUCCESS = 'REMOVE_FROM_FAVOURITE_SUCCESS';
const REMOVE_FROM_FAVOURITE_ERROR = 'REMOVE_FROM_FAVOURITE_ERROR';

const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
const ADD_TO_FAVOURITE_SUCCESS = 'ADD_TO_FAVOURITE_SUCCESS';
const ADD_TO_FAVOURITE_ERROR = 'ADD_TO_FAVOURITE_ERROR';

const GET_USER_RECIPES = 'GET_USER_RECIPES';
const GET_USER_RECIPES_SUCCESS = 'GET_USER_RECIPES_SUCCESS';
const GET_USER_RECIPES_ERROR = 'GET_USER_RECIPES_ERROR';

const UP_VOTE_RECIPE = 'UP_VOTE_RECIPE';
const UP_VOTE_RECIPE_SUCCESS = 'UP_VOTE_RECIPE_SUCCESS';
const UP_VOTE_RECIPE_ERROR = 'UP_VOTE_RECIPE_ERROR';

const DOWN_VOTE_RECIPE = 'DOWN_VOTE_RECIPE';
const DOWN_VOTE_RECIPE_SUCCESS = 'DOWN_VOTE_RECIPE_SUCCESS';
const DOWN_VOTE_RECIPE_ERROR = 'DOWN_VOTE_RECIPE_ERROR';

const POST_COMMENT = 'POST_COMMENT';
const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';

const GET_COMMENTS = 'GET_COMMENTS';
const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';

const DELETE_COMMENT = 'DELETE_COMMENT';
const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

const ADD_RECIPE_TO_FAVOURITE = 'ADD_RECIPE_TO_FAVOURITE';
const ADD_RECIPE_TO_FAVOURITE_SUCCESS = 'ADD_RECIPE_TO_FAVOURITE_SUCCESS';
const ADD_RECIPE_TO_FAVOURITE_ERROR = 'ADD_RECIPE_TO_FAVOURITE_ERROR';

const SEARCH_RECIPE = 'SEARCH_RECIPE';
const SEARCH_RECIPE_SUCCESS = 'SEARCH_RECIPE_SUCCESS';
const SEARCH_RECIPE_ERROR = 'SEARCH_RECIPE_ERROR';

const LOGOUT = 'LOGOUT';

/**
 * 
 * @description combines all action types and export
 * 
 */
export default {
  SIGN_UP,
  SIGN_UP_SUCCESS,
  SIGN_UP_ERROR,
  SIGN_IN,
  SIGN_IN_SUCCESS,
  SIGN_IN_ERROR,
  ADD_RECIPE,
  ADD_RECIPE_SUCCESS,
  ADD_RECIPE_ERROR,
  GET_ALL_RECIPES,
  GET_ALL_RECIPES_SUCCESS,
  GET_ALL_RECIPES_ERROR,
  GET_RECIPE,
  GET_RECIPE_SUCCESS,
  GET_RECIPE_ERROR,
  DELETE_RECIPE,
  DELETE_RECIPE_SUCCESS,
  DELETE_RECIPE_ERROR,
  MODIFY_RECIPE,
  MODIFY_RECIPE_SUCCESS,
  MODIFY_RECIPE_ERROR,
  GET_USER_FAVOURITE_RECIPES,
  GET_USER_FAVOURITE_RECIPES_SUCCESS,
  GET_USER_FAVOURITE_RECIPES_ERROR,
  ADD_TO_FAVOURITE,
  ADD_TO_FAVOURITE_SUCCESS,
  ADD_TO_FAVOURITE_ERROR,
  REMOVE_FROM_FAVOURITE,
  REMOVE_FROM_FAVOURITE_SUCCESS,
  REMOVE_FROM_FAVOURITE_ERROR,
  GET_USER_RECIPES,
  GET_USER_RECIPES_SUCCESS,
  GET_USER_RECIPES_ERROR,
  UP_VOTE_RECIPE,
  UP_VOTE_RECIPE_SUCCESS,
  UP_VOTE_RECIPE_ERROR,
  DOWN_VOTE_RECIPE,
  DOWN_VOTE_RECIPE_SUCCESS,
  DOWN_VOTE_RECIPE_ERROR,
  POST_COMMENT,
  POST_COMMENT_SUCCESS,
  POST_COMMENT_ERROR,
  GET_COMMENTS,
  GET_COMMENTS_SUCCESS,
  GET_COMMENTS_ERROR,
  DELETE_COMMENT,
  DELETE_COMMENT_SUCCESS,
  DELETE_COMMENT_ERROR,
  ADD_RECIPE_TO_FAVOURITE,
  ADD_RECIPE_TO_FAVOURITE_SUCCESS,
  ADD_RECIPE_TO_FAVOURITE_ERROR,
  LOGOUT,
  SEARCH_RECIPE,
  SEARCH_RECIPE_SUCCESS,
  SEARCH_RECIPE_ERROR
};
